language: ruby
sudo: required
dist: trusty
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-19mode
  - rbx-3
before_install: gem install bundler
matrix:
  allow_failures:
  - rvm: rbx-3
addons:
  apt:
    packages:
      - haveged
